##
# This workflow is triggered on a schedule and deletes old container images from the GitHub Container Registry.
##

name: ghcr-cleanup

on:
  workflow_call:
    inputs:
      dry-run:
        type: boolean
        default: true
        description: if true, no images will be deleted
    secrets:
      token:
        required: true
        description: GitHub PAT with repo permissions

jobs:
  ghcr-cleanup:
    name: Delete old container images
    runs-on: ubuntu-latest
    steps:
      - uses: dataaxiom/ghcr-cleanup-action@v1.0.15
        with:
          token: ${{ secrets.token }}
          owner: ${{ github.repository_owner }}
          package: ${{ github.event.repository.name }}
          #dry-run: ${{ inputs.dry_run }}
          use-regex: true
          exclude-tags: "^(v?(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?|main|latest)$"
          delete-untagged: true
          older-than: 30 days
          keep-n-untagged: 10
          dry-run: true
          validate: true